Updating color_enabled= to color=
This method deprecated, and produces an error message:

/Users/cgore/programming/ruby/pagerduty/spec/spec_helper.rb:8:in `block in <top (required)>': undefined method `color_enabled=' for #<RSpec::Core::Configuration:0x007fee8bc257f0> (NoMethodError)
	from /Users/cgore/.rvm/gems/ruby-1.9.3-p545/gems/rspec-core-3.0.3/lib/rspec/core.rb:79:in `configure'
	from /Users/cgore/programming/ruby/pagerduty/spec/spec_helper.rb:7:in `<top (required)>'
	from /Users/cgore/programming/ruby/pagerduty/spec/pagerduty/http_transport_spec.rb:2:in `require'
	from /Users/cgore/programming/ruby/pagerduty/spec/pagerduty/http_transport_spec.rb:2:in `<top (required)>'
	from /Users/cgore/.rvm/gems/ruby-1.9.3-p545/gems/rspec-core-3.0.3/lib/rspec/core/configuration.rb:1057:in `load'
	from /Users/cgore/.rvm/gems/ruby-1.9.3-p545/gems/rspec-core-3.0.3/lib/rspec/core/configuration.rb:1057:in `block in load_spec_files'
	from /Users/cgore/.rvm/gems/ruby-1.9.3-p545/gems/rspec-core-3.0.3/lib/rspec/core/configuration.rb:1057:in `each'
	from /Users/cgore/.rvm/gems/ruby-1.9.3-p545/gems/rspec-core-3.0.3/lib/rspec/core/configuration.rb:1057:in `load_spec_files'
	from /Users/cgore/.rvm/gems/ruby-1.9.3-p545/gems/rspec-core-3.0.3/lib/rspec/core/runner.rb:97:in `setup'
	from /Users/cgore/.rvm/gems/ruby-1.9.3-p545/gems/rspec-core-3.0.3/lib/rspec/core/runner.rb:85:in `run'
	from /Users/cgore/.rvm/gems/ruby-1.9.3-p545/gems/rspec-core-3.0.3/lib/rspec/core/runner.rb:70:in `run'
	from /Users/cgore/.rvm/gems/ruby-1.9.3-p545/gems/rspec-core-3.0.3/lib/rspec/core/runner.rb:38:in `invoke'
	from /Users/cgore/.rvm/gems/ruby-1.9.3-p545/gems/rspec-core-3.0.3/exe/rspec:4:in `<main>'
/Users/cgore/.rvm/rubies/ruby-1.9.3-p545/bin/ruby -I/Users/cgore/.rvm/gems/ruby-1.9.3-p545/gems/rspec-core-3.0.3/lib:/Users/cgore/.rvm/gems/ruby-1.9.3-p545/gems/rspec-support-3.0.3/lib -S /Users/cgore/.rvm/gems/ruby-1.9.3-p545/gems/rspec-core-3.0.3/exe/rspec ./spec/pagerduty/http_transport_spec.rb ./spec/pagerduty_spec.rb failed